all:
	go run program.go /Users/liujinshu/climate_data/berkeley_data_set/2010/data.csv -1 2330 0.75 120 1000 1000 1.00 0 8
all_0:
	go run program_0.go /Users/liujinshu/climate_data/berkeley_data_set/2010/data.csv -1 2330 0.75 168 1000 1000
server:
	go run program.go /u/jliu158/climate_data/data.csv -1 6000 0.75 120 5000 1000 1.00 0 8
server_0:
	go run program_0.go /u/jliu158/climate_data/data.csv -1 2330 0.75 168 1000 1000
